### ISSUE TITLE
Internal Display Blank With Flashing Cursor

### ISSUE THREAD

**Issue by SK1Y101** [ewagner12/all-ways-egpu#15]
Just setup all-ways-egpu on ubuntu mantic with no issues, GTX1080 with Nvidia-535 is workigf flawlessly on external monitors.

However, the internal display on my laptop (framework 12) is blank, with a single cursor showing in the top right corner.
I have verified that this only occurs when the eGPU is used as the primary display.

Am I misunderstanding something, or is it not possible to use the internal laptop display with the eGPU enabled?

If it is possible, what troubleshooting steps should i go through to enable this?

Thanks

**Comment by ewagner12** [comment]
Hi @SK1Y101 I believe this is a duplicate of #3 see that issue for more info. This appears to be an issue with the nvidia proprietary driver. I haven't tested it recently but you might have more luck with the nvidia-open driver

**Comment by SK1Y101** [comment]
Hi @ewagner12, thanks for the follow up. I'll try the nouveau drivers next!

**Comment by SK1Y101** [comment]
Just here to say switching to the open drivers and rebooting worked, but you do experience a performance penalty compared to the proprietary ones.

**Comment by MichalHecko** [comment]
Hello, same or similar issue still present. After using method 3, everything on external screen is flaweless, but internal display on notebook stay turned on with blank screen.

Has anybody similar experience ?

NVIDIA 555.58.02, mutter 46.4, GS 46.4 (Wayland), Kernel 6.10.4
