### ISSUE TITLE
Is there a way to get this to work with Silverblue?

### ISSUE THREAD

**Issue by nmcbride** [ewagner12/all-ways-egpu#17]
Hello,

I'm using Fedora Silverblue and can't really install this do to how silverblue works.
Is there anyway to get this to work with Silverblue?

Thank you.

**Comment by ewagner12** [comment]
Yes, see the Steam Deck/User Installation section of the readme. I've used it on Fedora Silverblue and it should work when installed this way.

**Comment by ewagner12** [comment]
@nmcbride 
Also note from that section:

> Automatic switching at bootup is not available with this type of installation so the script must be run by the user after login to switch to the eGPU

So right now when installed with the user-install option the script has to be run each time the computer is booted with the eGPU.

**Comment by nmcbride** [comment]
Thank you I'm sorry I completely missed that in the docs.
That would explain why the services are not running and not able to find the executable.

**Comment by ewagner12** [comment]
@nmcbride 
If there's interest in it I think I could add the functionality to make the systemd services and automatic switching work. Let me know if that's something you would be interested in.

**Comment by nmcbride** [comment]
I can't speak for others but I would at least be.
I was thinking maybe it could be done as a user service in the case of a user install.

Do you think we could also add a utility command that shows you which device is set as boot_vga?
Looks like we just need to loop over the devices in `/sys/bus/pci/devices` and check which one where `boot_vga` exists.
I'm sure you already know this but I didn't so I'm really just putting this here for anyone else who is looking. :)

**Comment by ewagner12** [comment]
Once setup, the "Status" menu option will show if the eGPU is set as boot_vga by indicating "eGPU currently active as primary with Method 2" if boot_vga is set to 1 on that card.

**Comment by nmcbride** [comment]
Oh I see it now, thank you.

**Comment by ewagner12** [comment]
@nmcbride 
Automatic switching with the systemd services is now supported on Silverblue with the latest release.
Install the latest from https://github.com/ewagner12/all-ways-egpu#steam-deckuser-installation
Then re-run all-ways-egpu setup and it should work.
