### ISSUE TITLE
'all-ways-egpu switch internal' not doing anything

### ISSUE THREAD

**Issue by Abragus** [ewagner12/all-ways-egpu#20]
I'm able to switch to the eGPU by running

```
sudo all-ways-egpu set-boot-vga egpu
sudo all-ways-egpu set-compositor-primary egpu

gnome-session-quit --no-prompt
```
or the equivalent in the menu system. I am also able to hot-unplug the eGPU using
```
sudo all-ways-egpu
3. Disable a GPU (Method 1)
2. Remove eGPU now? (May allow hot-unplug)
```
which of course also acts to restart the display manager. 

`all-ways-egpu -h` leads me to believe it's possible to run `sudo all-ways-egpu switch internal` to accomplish the same thing as using the menu above, but nothing seems to happen. `sudo all-ways-egpu switch egpu` seems to do the same thing as removing the iGPU in the menu (I haven't got that to work, the displays never come back on again), but switching to internal doesn't work. 

I'm running:

- Fedora Workstation 39
- Linux Kernel 6.8.7-200.fc39.x86_64
- Gnome 45.5 in Wayland
- Radeon RX 6800

Please let me know if any more information is needed, or if there is anything else I can try!

**Comment by ewagner12** [comment]
@Abragus 
Thanks for the report.
I'd rather not change the behavior of the existing command `switch internal` and instead I think it would be better to add another command like `switch force-internal` that does what you want and update the documentation to make it more clear what each command does. Say something like:
To have both iGPU and eGPU active: `sudo all-ways-egpu switch internal` 
To have iGPU only active and disable eGPU to allow for hot-unplug of eGPU: `sudo all-ways-egpu switch force-internal`

**Comment by ewagner12** [comment]
@Abragus I just pushed the changes to the github repo. It would help if you could test this git version to make sure it works for you before I make a release for everyone.
Install the git version as follows: https://github.com/ewagner12/all-ways-egpu?tab=readme-ov-file#git

**Comment by Abragus** [comment]
`sudo all-ways-egpu switch force-internal` seems to work perfectly for me! Thanks for the incredibly quick response! It's an awesome tool.

**Comment by ewagner12** [comment]
No problem. Just made a new release with the changes. Enjoy!
