### ISSUE TITLE
Setup with method 1 is not working when using Steam Deck/User Installation

### ISSUE THREAD

**Issue by Zetarancio** [ewagner12/all-ways-egpu#21]
Hello there, I think the script looks for /usr/bin/all-ways-egpu instead of /home/USER/bin/all-ways-egpu in line 563 and 565. Launching all-ways-egpu configure egpu/internal fixes the issue.

Thanks for you amazing work btw.

**Comment by ewagner12** [comment]
Thanks for reporting this bug. This should now be fixed in the latest release if you download the latest and run the setup again.
