### ISSUE TITLE
KDE 6 Wayland

### ISSUE THREAD

**Issue by kevinbburns** [ewagner12/all-ways-egpu#28]
For some reason, with the newer 6.9+, 6.10, and 6.11-rc0 kernels, the scripts are no longer working on setting the egpu as the primary renderer for KDE6.

**Comment by ewagner12** [comment]
@kevinbburns 
Could you post your system specs (laptop, egpu, etc) and what issue exactly your seeing?

I just quickly tested Fedora 40 with KDE Plasma 6.1 on my system and switching seemed to work ok. Only one of my 2 displays worked but the actual switching from the script worked fine

**Comment by fenKss** [comment]
I just tried it - everything works correctly. 2 external monitors (excluding laptop) + Nvidia + Wayland
```
Operating System: Arch Linux 
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.9.10-arch1-1 (64-bit)
Graphics Platform: Wayland
Graphics Processor: NVIDIA GeForce RTX 4070 Laptop GPU/PCIe/SSE2
```

**Comment by kevinbburns** [comment]
@ewagner12  https://egpu.io/forums/builds/2023-16-lenovo-thinkpad-z16-gen-2-rx6550m-r7k8ch-rx-7800-xt-64gbps-usb4v1-adt-link-ut3g-linux-fedora-39/

It's weird, it seems to be "working," but with previous versions of KDE6, in the "Info" section, it would report the eGPU as the main card for the compositor.

Now it shows the iGPU as the main compositor for KDE, but in the all-ways-egpu status, it shows correctly. On my 34" monitor, I am getting 144hz, and I def. know that the 780m would not be able to handle that refresh rate properly. Just odd I guess, but all seems good, just KDE info GUI doesn't know what to make of it.

![image](https://github.com/user-attachments/assets/5d774107-f1b5-41ab-953f-9238d23eb22a)

**Comment by kevinbburns** [comment]
> I just tried it - everything works correctly with 2 external monitors (excluding laptop)
> 
> ```
> Operating System: Arch Linux 
> KDE Plasma Version: 6.1.3
> KDE Frameworks Version: 6.4.0
> Qt Version: 6.7.2
> Kernel Version: 6.9.10-arch1-1 (64-bit)
> Graphics Platform: Wayland
> Graphics Processor: NVIDIA GeForce RTX 4070 Laptop GPU/PCIe/SSE2
> ```

If both monitors are plugged into the eGPU, and they are on, doesn't mean that your Nvidia GPU is doing the "work."  KDE will try to treat it like a system with hybrid graphics (Bumblebee, Prime) and it will perform all the rendering internaly on the iGPU and "relay" it to the external eGPU. 

In my case, both monitors have worked flawlessly, no matter what, and gaming has been 100%. I am getting a solid 144 FPS in Apex and some other triple A's, and the animations in the KDE DE are running flawless, so my gut tells me everything is good. 

Even running on my laptop, the 780m/6500m will stutter sometimes with the animations, just odd. It seems like the Mesa and Vulkan profiles are trying to default to the iGPU too, but 2 or 3 weeks ago, that was not the case. Something changed somewhere, trying to hunt it down.

**Comment by kevinbburns** [comment]
@ewagner12 If it helps, I can get you in with Teamviewer if you need to check anything out for debugging. As it stands right now, everything seems to be working with your scripts and setup, it seems like KDE has something else going on possilby. 

Let me know if you want me to close it out or if you want to keep digging.

**Comment by ewagner12** [comment]
@kevinbburns
One thing that did change starting with kernel 6.9 on the USB4 side is that the thunderbolt/USB4 tunnel is now reset during bootup rather than using what the firmware allocated: https://lore.kernel.org/linux-usb/20240106165723.3377789-1-Sanath.S@amd.com/
This could slightly change behavior of eGPU detection though I haven't seen anything on my end.

You could try adding the boot kernel parameter: `thunderbolt.host_reset=0`

See if that does anything to make it behave as it did before.

**Comment by kevinbburns** [comment]
Setting thunderbolt.host_reset=0 locked the display up before it would hit SDDM, so back to the drawing board. I think I am going to disable selinux for a little bit and dig into this, my gut is telling me something got messed up recently. I had to make some fstab changes, and let SE re-label everything, but I can't remember the timeline when either happened, so I will do my best to recreate it.

**Comment by kevinbburns** [comment]
After digging in some more, I had to add the following to /etc/default/grub:
` thunderbolt.host_reset=0 amdgpu.dc=1 amdgpu.sg_display=1 `
After that, using my original config file, I am all good:

![image](https://github.com/user-attachments/assets/82db3de2-d435-45fe-9ebc-bd932483b9b1)

Must have been an issue with the 6.9.9 kernel in Fedora 40
