### ISSUE TITLE
Configure eGPU as primary using boot_vga under Wayland desktops error

### ISSUE THREAD

**Issue by DizzieNight** [ewagner12/all-ways-egpu#32]
I'm getting this error when trying to start the script at boot. Not sure why or even how to?

![image](https://github.com/user-attachments/assets/940ef63c-51b8-4d57-a7ae-9cfa5b7dc455)

**Comment by ewagner12** [comment]
@DizzieNight 
That looks like the script is working correctly and it's just saying that it ran Method 2 to set the eGPU on 0000:81:00.0 as primary.
If the script is working properly you should see that the eGPU is now used by default for applications and any external displays connected to the eGPU may be smoother (though internal displays connected to the iGPU may be less smooth).

**Comment by DizzieNight** [comment]
Huh, strange because sometimes whenever I boot up my laptop it will use the egpu and sometimes it won't. I have tried resetting the config multiple times and rebooting multiple times and still no luck

**Comment by DizzieNight** [comment]
I think I've got it working now. There was an issue with my laptop not loading the kernel modules. Thank you for your help
