### ISSUE TITLE
Bund mounts not actually set or removed

### ISSUE THREAD

**Issue by The-SamminAter** [ewagner12/all-ways-egpu#5]
I currently have all-ways-egpu use method two, and happened to notice that it doesn't actually work. If I had to guess, it would be because the tool doesn't actually set or remove bind mounts. Here is the output of the status page:
```
Started Configure eGPU as primary using boot_vga under Wayland desktops.
Existing bind mounts recorded. Removing...
umount: /sys/bus/pci/devices/0000:84:00.0/drm/card*/device/boot_vga: no mount point specified.
Bind mounts removed successfully. Restart Display Manager for changes to take effect.
/usr/bin/all-ways-egpu: line 237: /sys/bus/pci/devices/0000:00:02.0/drm/card*/device/boot_vga: No such file or directory
/sys/bus/pci/devices/0000:84:00.0/drm/card*/device
mount: /sys/bus/pci/devices/0000:84:00.0/drm/card*/device/boot_vga: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
Bind mounts set. Restart Display Manager for changes to take effect.
all-ways-egpu-boot-vga.service: Deactivated successfully.
```
Not sure why this happens, but I figured I'd let you know.

**Comment by ewagner12** [comment]
It looks to me like the script is trying to create and remove the bind mounts, but the issue is that it can't find the locations of the files.
If you want more help on tracking down this issue, it would help to look at the output of lspci to make sure 84:00.0 and 00:02.0 are the correct addresses of the eGPU and iGPU.
Are you using bash as your shell or a different shell?

**Comment by The-SamminAter** [comment]
I'm using zsh as my shell, but I have bash installed in all of the regular paths. As for the addresses, I used the auto-configuration tool to get them, but running `lspci -k | grey -EA3 'VGA|3D|Display'` confirms them.

For reference, here's the output of the above command:

**Comment by ewagner12** [comment]
Ok thanks, besides this script issue is the eGPU working? For example does it output a display or anything?
And could you post the output of: ls /sys/bus/pci/devices/0000:84:00.0/drm

**Comment by The-SamminAter** [comment]
Yes, the eGPU works just fine, however, it is connected directly to my monitor, and if the Intel iGPU is GPU 0 the monitor is laggy.

The output is as follows: `card1  controlD65  RenderD129`

I believe the issue lies in line 230, where it would seem you can't use the * like you have tried to. There are other ways to get the listing/name of a file that would work, ranging from not suggested (grepping ls) to better (checking if card0 or card1 exists, and then using the one that exists). The method is up to you, but I'm relatively sure that the script does not work in it's current state.

**Comment by The-SamminAter** [comment]
It didn't throw an error this time, lets see if it works.

**Comment by The-SamminAter** [comment]
It seems to work. Thanks for the suggestion and this tool.
